### ISSUE TITLE
Support many-to-one relationship between organisation and customer

### ISSUE THREAD

**Issue by iokiwi** [iokiwi/jsd-bulk-customer-upload#18]
Raised by @patrijst here -> https://github.com/iokiwi/jsd-bulk-customer-upload/issues/16

> Awesome, working on a project for a customer where your script is very
> useful, would like to use it first week of January.
> It would also be great if duplicate customer accounts would be accepted, so
> they can be a part of multiple organizations.
>
> Organization | Name | Address
> A | John Doe | john.doe@local
> B | John Doe | john.doe@local

**Comment by iokiwi** [comment]
More or less done. It should be possible to specify multiple relationships by including multiple rows in your csv

**Comment by patrijst** [comment]
Awesome!! Do you have an example CSV I can use to test?

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 3 January 2021 at 14:29:07, Simon Merrick (notifications@github.com)
wrote:

More or less done. It should be possible to specify multiple relationships
by including multiple rows in your csv

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-753617309>,
or unsubscribe

**Comment by iokiwi** [comment]
Patrijst, basically as you specified.

```csv
Organization,Name,Address
A,John Doe,john.doe@local
B,John Doe,john.doe@local
```

For each row script will

1. Create org if not exists
2. Create user if not exists
3. Assign user to org

End result will be 1 user and two orgs exist. User is member of both orgs.

Note you will probably need to specify both the name and email address for the user on both rows It may work with just the email but I didn't check.

Just to check are you using Jira cloud or server and if server, which version? I tested against cloud but the server version might need a bit more work.

**Comment by patrijst** [comment]
Thank you!

For this specific case I'm using Cloud but we have had customers wanting
this for Server as well. I have my own (messy) python script that can do
that but it didn't work for Cloud due to the resources (max 50) issue which
you neatly solved.

I've tested the scenarios of both duplicate customers to different orgs and
customers not related to any org and both are added, you are awesome

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 4 January 2021 at 10:14:49, Simon Merrick (notifications@github.com)
wrote:

Patrijst, basically as you specified.

Organization,Name,Address
A,John Doe,john.doe@local
B,John Doe,john.doe@local

For each row script will

   1. Create org if not exists
   2. Create user if not exists
   3. Assign user to org

End result will be 1 user and two orgs exist. User is member of both orgs.

Just to check are you using Jira cloud or server and if server, which
version? I tested against cloud but the server version might need a bit
more work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-753856915>,
or unsubscribe

**Comment by iokiwi** [comment]
Glad to help.

This may already work for server otherwise it shouldn't take too much more effort to make it work for server. I didn't get round to testing.

I got a little disheartened because

1. I was trying to abstract differences between server and cloud versions but cloud has diverged from server quite significantly so this took a lot more time and effort than anticipated.

2. With all the abstractions this project has sort of lost one of the benefits which was that even if the script didn't just work out of the box, it was easy enough to read / understand what it was doing so you could modify it / write your own. It served as sample code but now with all the abstractions is harder to follow.

It would probably be much much simpler just to write separate scripts for cloud and server.

**Comment by patrijst** [comment]
Hi Simon,

I got a ton of rows with the following error.. other rows processed just
fine, any idea why?

[1/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Creating customer:
Name: a.b.h.bootsveld@vwtelecom.co
Email a.b.h.bootsveld@vwtelecom.com
['email : An account already exists for this email']
Adding a.b.h.bootsveld@vwtelecom.com to the service desk
2021-01-19 12:24:13,187 - ERROR - bulk_customer_import.bulk_customer_import
- Failed to process row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Traceback (most recent call last):
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 96, in main
    servicedesk_id, customer.to_dict())
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/servicedesk.py",
line 58, in add_customer
    account_id = customer.get_account_id()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/customer.py",
line 146, in get_account_id
    self.account_id = customer.account_id
AttributeError: 'NoneType' object has no attribute 'account_id'

[2/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.babur@vwtelecom.com', 'a.babur@vwtelecom.com']
Creating customer:
Name: a.babur@vwtelecom.com
Email a.babur@vwtelecom.com
['email : An account already exists for this email']
Adding a.babur@vwtelecom.com to the service desk
Organization already exists: VolkerWessels Telecom Infratechniek

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 4 January 2021 at 10:52:25, Simon Merrick (notifications@github.com)
wrote:

Glad to help.

This may already work for server otherwise it shouldn't take too much more
effort to make it work for server. I didn't get round to testing.

I got a little disheartened because

   1.

   I was trying to abstract differences between server and cloud versions
   but cloud has diverged from server quite significantly so this took a lot
   more time and effort than anticipated.
   2.

   With all the abstractions this project has sort of lost one of the
   benefits which was that even if the script didn't just work out of the box,
   it was easy enough to read / understand what it was doing so you could
   modify it / write your own. It served as sample code but now with all the
   abstractions is harder to follow.

It would probably be much much simpler just to write separate scripts for
cloud and server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-753875345>,
or unsubscribe

**Comment by patrijst** [comment]
Could it be due to naming of orgs that are similar?




Removing the organization does not work either..

[3/3] Processing row: ['', 'A.Bergsma@bam.nl', 'A.Bergsma@bam.nl']
Creating customer:
Name: A.Bergsma@bam.nl
Email A.Bergsma@bam.nl
['email : An account already exists for this email']
Adding A.Bergsma@bam.nl to the service desk
2021-01-19 13:08:29,970 - ERROR - bulk_customer_import.bulk_customer_import
- Failed to process row: ['', 'A.Bergsma@bam.nl', 'A.Bergsma@bam.nl']
Traceback (most recent call last):
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 96, in main
    servicedesk_id, customer.to_dict())
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/servicedesk.py",
line 58, in add_customer
    account_id = customer.get_account_id()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/customer.py",
line 146, in get_account_id
    self.account_id = customer.account_id
AttributeError: 'NoneType' object has no attribute 'account_id'
An error occurred while processing the following rows.
['VolkerWessels Telecom Infratechniek', 'a.b.h.bootsveld@vwtelecom.co', '
a.b.h.bootsveld@vwtelecom.com']

CSV

Organisation Name,Customer Full Name,Customer Email
VolkerWessels Telecom Infratechniek,a.b.h.bootsveld@vwtelecom.co,
a.b.h.bootsveld@vwtelecom.com
VolkerWessels Telecom Infratechniek,a.babur@vwtelecom.com,
a.babur@vwtelecom.com
,A.Bergsma@bam.nl,A.Bergsma@bam.nl

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 19 January 2021 at 12:25:34, Patrick van der Rijst (p.rijst@avisi.nl)
wrote:

Hi Simon,

I got a ton of rows with the following error.. other rows processed just
fine, any idea why?

[1/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Creating customer:
Name: a.b.h.bootsveld@vwtelecom.co
Email a.b.h.bootsveld@vwtelecom.com
['email : An account already exists for this email']
Adding a.b.h.bootsveld@vwtelecom.com to the service desk
2021-01-19 12:24:13,187 - ERROR - bulk_customer_import.bulk_customer_import
- Failed to process row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Traceback (most recent call last):
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 96, in main
    servicedesk_id, customer.to_dict())
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/servicedesk.py",
line 58, in add_customer
    account_id = customer.get_account_id()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/customer.py",
line 146, in get_account_id
    self.account_id = customer.account_id
AttributeError: 'NoneType' object has no attribute 'account_id'

[2/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.babur@vwtelecom.com', 'a.babur@vwtelecom.com']
Creating customer:
Name: a.babur@vwtelecom.com
Email a.babur@vwtelecom.com
['email : An account already exists for this email']
Adding a.babur@vwtelecom.com to the service desk
Organization already exists: VolkerWessels Telecom Infratechniek

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 4 January 2021 at 10:52:25, Simon Merrick (notifications@github.com)
wrote:

Glad to help.

This may already work for server otherwise it shouldn't take too much more
effort to make it work for server. I didn't get round to testing.

I got a little disheartened because

   1.

   I was trying to abstract differences between server and cloud versions
   but cloud has diverged from server quite significantly so this took a lot
   more time and effort than anticipated.
   2.

   With all the abstractions this project has sort of lost one of the
   benefits which was that even if the script didn't just work out of the box,
   it was easy enough to read / understand what it was doing so you could
   modify it / write your own. It served as sample code but now with all the
   abstractions is harder to follow.

It would probably be much much simpler just to write separate scripts for
cloud and server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-753875345>,
or unsubscribe

**Comment by patrijst** [comment]
It seems to fail for users that already exist on the site but are not
active. These need to be removed first I believe.

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 19 January 2021 at 13:10:58, Patrick van der Rijst (p.rijst@avisi.nl)
wrote:

Could it be due to naming of orgs that are similar?




Removing the organization does not work either..

[3/3] Processing row: ['', 'A.Bergsma@bam.nl', 'A.Bergsma@bam.nl']
Creating customer:
Name: A.Bergsma@bam.nl
Email A.Bergsma@bam.nl
['email : An account already exists for this email']
Adding A.Bergsma@bam.nl to the service desk
2021-01-19 13:08:29,970 - ERROR - bulk_customer_import.bulk_customer_import
- Failed to process row: ['', 'A.Bergsma@bam.nl', 'A.Bergsma@bam.nl']
Traceback (most recent call last):
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 96, in main
    servicedesk_id, customer.to_dict())
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/servicedesk.py",
line 58, in add_customer
    account_id = customer.get_account_id()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/customer.py",
line 146, in get_account_id
    self.account_id = customer.account_id
AttributeError: 'NoneType' object has no attribute 'account_id'
An error occurred while processing the following rows.
['VolkerWessels Telecom Infratechniek', 'a.b.h.bootsveld@vwtelecom.co', '
a.b.h.bootsveld@vwtelecom.com']

CSV

Organisation Name,Customer Full Name,Customer Email
VolkerWessels Telecom Infratechniek,a.b.h.bootsveld@vwtelecom.co,
a.b.h.bootsveld@vwtelecom.com
VolkerWessels Telecom Infratechniek,a.babur@vwtelecom.com,
a.babur@vwtelecom.com
,A.Bergsma@bam.nl,A.Bergsma@bam.nl

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 19 January 2021 at 12:25:34, Patrick van der Rijst (p.rijst@avisi.nl)
wrote:

Hi Simon,

I got a ton of rows with the following error.. other rows processed just
fine, any idea why?

[1/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Creating customer:
Name: a.b.h.bootsveld@vwtelecom.co
Email a.b.h.bootsveld@vwtelecom.com
['email : An account already exists for this email']
Adding a.b.h.bootsveld@vwtelecom.com to the service desk
2021-01-19 12:24:13,187 - ERROR - bulk_customer_import.bulk_customer_import
- Failed to process row: ['VolkerWessels Telecom Infratechniek', '
a.b.h.bootsveld@vwtelecom.co', 'a.b.h.bootsveld@vwtelecom.com']
Traceback (most recent call last):
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 96, in main
    servicedesk_id, customer.to_dict())
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/servicedesk.py",
line 58, in add_customer
    account_id = customer.get_account_id()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/customer.py",
line 146, in get_account_id
    self.account_id = customer.account_id
AttributeError: 'NoneType' object has no attribute 'account_id'

[2/3] Processing row: ['VolkerWessels Telecom Infratechniek', '
a.babur@vwtelecom.com', 'a.babur@vwtelecom.com']
Creating customer:
Name: a.babur@vwtelecom.com
Email a.babur@vwtelecom.com
['email : An account already exists for this email']
Adding a.babur@vwtelecom.com to the service desk
Organization already exists: VolkerWessels Telecom Infratechniek

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 4 January 2021 at 10:52:25, Simon Merrick (notifications@github.com)
wrote:

Glad to help.

This may already work for server otherwise it shouldn't take too much more
effort to make it work for server. I didn't get round to testing.

I got a little disheartened because

   1.

   I was trying to abstract differences between server and cloud versions
   but cloud has diverged from server quite significantly so this took a lot
   more time and effort than anticipated.
   2.

   With all the abstractions this project has sort of lost one of the
   benefits which was that even if the script didn't just work out of the box,
   it was easy enough to read / understand what it was doing so you could
   modify it / write your own. It served as sample code but now with all the
   abstractions is harder to follow.

It would probably be much much simpler just to write separate scripts for
cloud and server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-753875345>,
or unsubscribe

**Comment by iokiwi** [comment]
Hey @patrijst sorry I just saw this. I'll look into it in the next week (I am away hiking over the weekend) 

Can you confirm what version of JSD you are using? Either `cloud` or the version number of jira service desk if its server.

**Comment by patrijst** [comment]
Hey Simon!

Hope you're having a great time hiking!

I was running into this error when users have been imported using the CSV
import but you leave them inactive.
Then, try to import the same e-mail adres as a JSD customer and that fails.

Using Cloud.

I've already sorted this manually for the users we needed to import but
would be good to review.

The "connection refused" part still occurred from time to time, I had to
import ~1500 customers.

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 22 January 2021 at 12:11:23, Simon Merrick (notifications@github.com)
wrote:

Hey @patrijst <https://github.com/patrijst> sorry I just saw this. I'll
look into it in the next week (I am away hiking over the weekend)

Can you confirm what version of JSD you are using? Either cloud or the
version number of jira service desk if its server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-765329059>,
or unsubscribe

**Comment by patrijst** [comment]
Hi there!

I'm trying to do another upload to Cloud but I'm facing this error:

jsd-bulk-customer-upload git:(master) ✗ python3.9 -m bulk_customer_import  \
  "https://pwfdiensten.atlassian.net" \
  ***@***.***" \
  "<pwd goes here>" \
  example1.csv \
  5
Traceback (most recent call last):
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 87, in _run_code
    exec(code, run_globals)
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/__main__.py",
line 2, in <module>
    bulk_customer_import.main()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 59, in main
    organizations = client.organization.list()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/organization.py",
line 17, in list
    return self.client.get_paginated_resource(
  File "/Users/patrijst/Projects/jsd-bulk-customer-upload/client/base.py",
line 85, in get_paginated_resource
    response = self.get(url, params=params, **kwargs).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line
900, in json
    return complexjson.loads(self.text, **kwargs)
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py",
line 346, in loads
    return _default_decoder.decode(s)
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have installed the requirements:

 pip3.9 install -r requirements.txt
Collecting requests>=2.23.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.1 MB/s
Collecting black>=19.10b0
  Downloading black-20.8b1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting flake8>=3.7.9
  Downloading flake8-3.9.0-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 1.3 MB/s
Collecting typed-ast>=1.4.0
  Downloading typed_ast-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (225 kB)
     |████████████████████████████████| 225 kB 625 kB/s
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting click>=7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.0 MB/s
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting regex>=2020.1.8
  Downloading regex-2021.4.4-cp39-cp39-macosx_10_9_x86_64.whl (284 kB)
     |████████████████████████████████| 284 kB 260 kB/s
Collecting toml>=0.10.1
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pycodestyle<2.8.0,>=2.7.0
  Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.2 MB/s
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.4.0,>=2.3.0
  Downloading pyflakes-2.3.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 1.6 MB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 1.4 MB/s
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
/Users/patrijst/Library/Python/3.9/lib/python/site-packages (from
requests>=2.23.0->-r requirements.txt (line 1)) (1.25.11)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.1 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 3.2 MB/s
Building wheels for collected packages: black
  Building wheel for black (PEP 517) ... done
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl
size=124184
sha256=0c573c01721563bec4eed59412b6ea0ffaa69a65d7801430440c498bdb810a53
  Stored in directory:
/Users/patrijst/Library/Caches/pip/wheels/4e/57/9a/e704bdd859ee892dc46fff03fd499422dc9e99fd9bd5c446d3
Successfully built black
Installing collected packages: typing-extensions, typed-ast, toml, regex,
pyflakes, pycodestyle, pathspec, mypy-extensions, mccabe, idna, click,
chardet, certifi, appdirs, requests, flake8, black
Successfully installed appdirs-1.4.4 black-20.8b1 certifi-2020.12.5
chardet-4.0.0 click-7.1.2 flake8-3.9.0 idna-2.10 mccabe-0.6.1
mypy-extensions-0.4.3 pathspec-0.8.1 pycodestyle-2.7.0 pyflakes-2.3.1
regex-2021.4.4 requests-2.25.1 toml-0.10.2 typed-ast-1.4.2
typing-extensions-3.7.4.3

Any idea?

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 22 January 2021 at 12:13:20, Patrick van der Rijst ***@***.***)
wrote:

Hey Simon!

Hope you're having a great time hiking!

I was running into this error when users have been imported using the CSV
import but you leave them inactive.
Then, try to import the same e-mail adres as a JSD customer and that fails.

Using Cloud.

I've already sorted this manually for the users we needed to import but
would be good to review.

The "connection refused" part still occurred from time to time, I had to
import ~1500 customers.

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 22 January 2021 at 12:11:23, Simon Merrick ***@***.***)
wrote:

Hey @patrijst <https://github.com/patrijst> sorry I just saw this. I'll
look into it in the next week (I am away hiking over the weekend)

Can you confirm what version of JSD you are using? Either cloud or the
version number of jira service desk if its server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-765329059>,
or unsubscribe

**Comment by patrijst** [comment]
Found it.. had to use my OAuth credentials instead of basic authentication.
Perhaps catch the 401 and return that?

With -l DEBUG;

2021-04-06 15:31:50,560 - DEBUG - urllib3.connectionpool -
https://pwfdiensten.atlassian.net:443 "GET
/rest/servicedeskapi/organization?start=0 HTTP/1.1" 401 None
Traceback (most recent call last):
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 197, in _run_module_as_main

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 6 April 2021 at 14:53:53, Patrick van der Rijst ***@***.***) wrote:

Hi there!

I'm trying to do another upload to Cloud but I'm facing this error:

jsd-bulk-customer-upload git:(master) ✗ python3.9 -m bulk_customer_import  \
  "https://pwfdiensten.atlassian.net" \
  ***@***.***" \
  "<pwd goes here>" \
  example1.csv \
  5
Traceback (most recent call last):
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 87, in _run_code
    exec(code, run_globals)
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/__main__.py",
line 2, in <module>
    bulk_customer_import.main()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 59, in main
    organizations = client.organization.list()
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/organization.py",
line 17, in list
    return self.client.get_paginated_resource(
  File "/Users/patrijst/Projects/jsd-bulk-customer-upload/client/base.py",
line 85, in get_paginated_resource
    response = self.get(url, params=params, **kwargs).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line
900, in json
    return complexjson.loads(self.text, **kwargs)
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py",
line 346, in loads
    return _default_decoder.decode(s)
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ***@***.***/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have installed the requirements:

 pip3.9 install -r requirements.txt
Collecting requests>=2.23.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.1 MB/s
Collecting black>=19.10b0
  Downloading black-20.8b1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting flake8>=3.7.9
  Downloading flake8-3.9.0-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 1.3 MB/s
Collecting typed-ast>=1.4.0
  Downloading typed_ast-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (225 kB)
     |████████████████████████████████| 225 kB 625 kB/s
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting click>=7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.0 MB/s
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting regex>=2020.1.8
  Downloading regex-2021.4.4-cp39-cp39-macosx_10_9_x86_64.whl (284 kB)
     |████████████████████████████████| 284 kB 260 kB/s
Collecting toml>=0.10.1
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pycodestyle<2.8.0,>=2.7.0
  Downloading pycodestyle-2.7.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.2 MB/s
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.4.0,>=2.3.0
  Downloading pyflakes-2.3.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 1.6 MB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 1.4 MB/s
Requirement already satisfied: urllib3<1.27,>=1.21.1 in
/Users/patrijst/Library/Python/3.9/lib/python/site-packages (from
requests>=2.23.0->-r requirements.txt (line 1)) (1.25.11)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.1 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 3.2 MB/s
Building wheels for collected packages: black
  Building wheel for black (PEP 517) ... done
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl
size=124184
sha256=0c573c01721563bec4eed59412b6ea0ffaa69a65d7801430440c498bdb810a53
  Stored in directory:
/Users/patrijst/Library/Caches/pip/wheels/4e/57/9a/e704bdd859ee892dc46fff03fd499422dc9e99fd9bd5c446d3
Successfully built black
Installing collected packages: typing-extensions, typed-ast, toml, regex,
pyflakes, pycodestyle, pathspec, mypy-extensions, mccabe, idna, click,
chardet, certifi, appdirs, requests, flake8, black
Successfully installed appdirs-1.4.4 black-20.8b1 certifi-2020.12.5
chardet-4.0.0 click-7.1.2 flake8-3.9.0 idna-2.10 mccabe-0.6.1
mypy-extensions-0.4.3 pathspec-0.8.1 pycodestyle-2.7.0 pyflakes-2.3.1
regex-2021.4.4 requests-2.25.1 toml-0.10.2 typed-ast-1.4.2
typing-extensions-3.7.4.3

Any idea?

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 22 January 2021 at 12:13:20, Patrick van der Rijst ***@***.***)
wrote:

Hey Simon!

Hope you're having a great time hiking!

I was running into this error when users have been imported using the CSV
import but you leave them inactive.
Then, try to import the same e-mail adres as a JSD customer and that fails.

Using Cloud.

I've already sorted this manually for the users we needed to import but
would be good to review.

The "connection refused" part still occurred from time to time, I had to
import ~1500 customers.

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 22 January 2021 at 12:11:23, Simon Merrick ***@***.***)
wrote:

Hey @patrijst <https://github.com/patrijst> sorry I just saw this. I'll
look into it in the next week (I am away hiking over the weekend)

Can you confirm what version of JSD you are using? Either cloud or the
version number of jira service desk if its server.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18#issuecomment-765329059>,
or unsubscribe

**Comment by iokiwi** [comment]
Yeah I was going to say, the problem is this line here: https://github.com/iokiwi/jsd-bulk-customer-upload/blob/master/client/base.py#L85

It's expecting json content from a successfull response but doesn't handle possible failures gracefully.

I will try fix it in the near future - pull request alyways welcome in the meantime :)
